// AllSpeak_Webson is a rendering engine for JSON-based markup scripts.

// The main entry point is AllSpeak_Webson.render(), which takes a container element,
// a name for the script, the script itself, and an optional options object.
// The script is a JSON object that describes the structure of the DOM
// to be created, along with any dynamic content or behavior.
// The script can include directives such as #element to specify
// the type of element to create, #content to specify the inner HTML
// or value of an element, #repeat to create multiple instances of an element
// based on an array, and #include to include another script.
// The AllSpeak_Webson engine processes the script recursively,
// building the DOM structure and applying any dynamic content or behavior
// as specified in the script.

// AllSpeak_Webson scripts can easily be generated by AI tools,
// allowing for dynamic and data-driven user interfaces.
// If you wish to take advantage of this you may need to 
// provide the AI engine with a link to the AllSpeak_Webson repository
// (https://github.com/allspeak/webson)
// for training purposes.
    
    const AllSpeak_Webson = {
    
    // Expand all variables in a value.
    // Expressions inside angle braces are fed to eval().
    expand: (element, input, symbols) => {
        let output = input;
        let mod = true;
        let values;
        let changed = false;
        if (typeof input === `object`) {
            const keys = Object.keys(input);
            for (let key of keys) {
                switch (key) {
                    case `#select`:
                        // Process an array selector
                        const value = AllSpeak_Webson.expand(element, input[key], symbols);
                        const index = input[`#index`];
                        if (typeof index === `undefined`) {
                            throw Error(`#select '${input[key]} has no #index`);
                        }
                        output = value[AllSpeak_Webson.expand(element, index, symbols)];
                        mod = true;
                        changed = true;
                        break;
                    default:
                        break;
                }
            }
        } else {
            while (mod) {
                mod = false;
                re = /(?:\#|\$)[a-zA-Z0-9_.]*/g;
                while ((values = re.exec(output)) !== null) {
                    let item = values[0];
                    switch (item[0]) {
                        case `#`:
                            // Evaluate system values
                            switch (item) {
                                case `#element_width`:
                                    output = output.replace(item, element.offsetWidth);
                                    mod = true;
                                    changed = true;
                                    break;
                                case `#parent_width`:
                                    output = output.replace(
                                        item, element.parentElement.offsetWidth);
                                    mod = true;
                                    changed = true;
                                    break;
                                case `#random`:
                                    output = output.replace(item, Math.floor(Math.random() * 10));
                                    mod = true;
                                    changed = true;
                                    break;
                                case `#step`:
                                    output = output.replace(item, symbols[`#step`]);
                                    mod = true;
                                    changed = true;
                                    break;
                                default:
                                    break;
                            }
                            break;
                        case `$`:
                            let value = item;
                            const val = symbols[item];
                            if (Array.isArray(val)) {
                                output = val;
                            } else {
                                value = AllSpeak_Webson.expand(element, val, symbols);
                                output = output.replace(item, value);
                            }
                            mod = true;
                            changed = true;
                            break;
                        default:
                            break;
                    }
                }
            }
        }
        // Remove braces. Try to evaluate their contents.
        // If this doesn't work, assume it's a value that can't be further simplified.
        changed = true;
        while (changed) {
            changed = false;
            try {
                const p = output.lastIndexOf(`<`);
                if (p >= 0) {
                    const q = output.indexOf(`>`, p);
                    if (q < 0) {
                        throw Error(`Mismatched braces in ${input}`);
                    }
                    const substr = output.substring(p + 1, q);
                    if (!['b', '/b', 'i', '/i', 'br', '/br'].includes(substr)) {
                        let repl = `<${substr}>`;
                        try {
                            const v = eval(substr);
                            output = output.replace(repl, v);
                        } catch (e) {
                            output = output.replace(repl, substr);
                        }
                        changed = true;
                    }
                }
            }
            catch (e) {
            }
        }
        return output;
    },
    
    // Get the definitions from a set of items
    getDefinitions: (items, symbols) => {
        const keys = Object.keys(items);
        for (let key of keys) {
            if (key[0] === `$`) {
                symbols[key] = items[key];
            }
        }
    },
    
    // Include another script
    include: async (parent, name, path, symbols) => {
        if (symbols[`#debug`] >= 2) {
            console.log(`#include ${name}: ${path}`);
        }
        const response = await fetch(path, {
            cache: `no-store`
        });
        const script = await response.text();
        await AllSpeak_Webson.build(parent, name, JSON.parse(script), symbols);
    },

    // Cache for external text files
    textCache: {},

    // Load text content from file (cached)
    loadTextFile: async (path) => {
        if (typeof AllSpeak_Webson.textCache[path] !== `undefined`) {
            return AllSpeak_Webson.textCache[path];
        }
        const response = await fetch(path, {
            cache: `no-store`
        });
        if (!response.ok) {
            throw Error(`Unable to load text file '${path}' (${response.status})`);
        }
        const text = await response.text();
        AllSpeak_Webson.textCache[path] = text;
        return text;
    },

    // Resolve $variables backed by external text files
    resolveFileBackedSymbols: async (items, symbols, element) => {
        for (const key of Object.keys(items)) {
            if (key[0] !== `$`) {
                continue;
            }
            const def = items[key];
            if (typeof def !== `object` || Array.isArray(def) || def === null) {
                continue;
            }
            const filePathSpec = typeof def[`#textFile`] !== `undefined`
                ? def[`#textFile`]
                : def[`#file`];
            if (typeof filePathSpec === `undefined`) {
                continue;
            }
            const filePath = AllSpeak_Webson.expand(element, filePathSpec, symbols);
            const text = await AllSpeak_Webson.loadTextFile(filePath);
            items[key] = text;
            symbols[key] = text;
            if (symbols[`#debug`] >= 2) {
                console.log(`File variable ${key}: ${filePath}`);
            }
        }
    },

    waitForElementReady: (element) => {
        if (!element || element.tagName !== `IMG`) {
            return Promise.resolve();
        }
        if (element.complete) {
            return Promise.resolve();
        }
        const timeoutMs = 5000;
        return new Promise(resolve => {
            let finished = false;
            const finish = () => {
                if (finished) {
                    return;
                }
                finished = true;
                element.removeEventListener(`load`, finish);
                element.removeEventListener(`error`, finish);
                resolve();
            };
            element.addEventListener(`load`, finish);
            element.addEventListener(`error`, finish);
            setTimeout(finish, timeoutMs);
        });
    },

    nowMs: () => {
        if (typeof performance !== `undefined` && typeof performance.now === `function`) {
            return performance.now();
        }
        return Date.now();
    },

    timingEnabled: false,

    timingReporter: null,

    reportTiming: (message) => {
        if (!AllSpeak_Webson.timingEnabled) {
            return;
        }
        if (typeof AllSpeak_Webson.timingReporter === `function`) {
            AllSpeak_Webson.timingReporter(message);
        } else {
            console.log(message);
        }
    },

    // Build a DOM structure
    build: async (parent, name, items, parentSymbols) => {
        const buildStartedAt = AllSpeak_Webson.nowMs();
        if (typeof parent === `undefined`) {
            throw Error(`build: 'parent' is undefined`);
        }
        if (typeof name === `undefined`) {
            throw Error(`build: element is undefined (is the #element directive missing?`);
        }
        if (typeof items === `undefined`) {
            throw Error(`build: ${name} has no properties`);
        }
        const symbols = JSON.parse(JSON.stringify(parentSymbols));
        AllSpeak_Webson.getDefinitions(items, symbols);
        await AllSpeak_Webson.resolveFileBackedSymbols(items, symbols, parent);
        if (typeof items[`#debug`] !== `undefined`) {
            symbols[`#debug`] = items[`#debug`];
        }
        if (symbols[`#debug`] >= 2) {
            console.log(`Build ${name}`);
        }
        if (typeof items[`#doc`] !== `undefined` && symbols[`#debug`] >= 1) {
            console.log(items[`#doc`]);
        }

        let element = parent;
        const elementType = items[`#element`];
        if (typeof elementType !== `undefined`) {
            if (symbols[`#debug`] >= 2) {
                console.log(`#element: ${elementType}`);
            }
            element = document.createElement(elementType);
            parent.appendChild(element);
        }
        symbols[`#element`] = element;

        for (const key of Object.keys(items)) {
            let value = items[key];
            switch (key) {
                case `#`:
                case `#debug`:
                case `#doc`:
                case `#element`:
                    break;
                case `#content`:
                    var val = ``;
                    if (Array.isArray(value)) {
                        for (const item of value) {
                            val += AllSpeak_Webson.expand(element, item, symbols);
                        }
                    } else {
                        val = AllSpeak_Webson.expand(element, value, symbols);
                    }
                    if (symbols[`#debug`] >= 2) {
                        console.log(`#content: ${value} -> ${val}`);
                    }
                    symbols[value] = val;
                    switch (element.type) {
                        case `text`:
                        case `textarea`:
                        case `input`:
                            element.value = val;
                            break;
                        default:
                            element.innerHTML = val;
                            break;
                    }
                    break;
                case `#repeat`:
                    symbols[`#steps`] = 0;
                    for (let item in value) {
                        switch (item) {
                            case `#doc`:
                                if (symbols[`#debug`] >= 1) {
                                    console.log(value[item]);
                                }
                                break;
                            case `#target`:
                                symbols[`#target`] = value[item];
                                break;
                            case `#steps`:
                                const stepspec = value[item];
                                for (let stepitem in stepspec) {
                                    switch (stepitem) {
                                        case `#arraysize`:
                                            const targetName = stepspec[stepitem];
                                            symbols[`#steps`] = symbols[targetName].length;
                                            break;
                                        default:
                                            break;
                                    }
                                }
                                break;
                            default:
                                break;
                        }
                    }
                    if (symbols[`#debug`] >= 2) {
                        console.log(`#repeat: ${symbols[`#target`]}, ${symbols[`#steps`]}`);
                    }
                    for (let step = 0; step < symbols[`#steps`]; step++) {
                        symbols[`#step`] = step;
                        await AllSpeak_Webson.build(element, `${name}[${step}]`, symbols[symbols[`#target`]], symbols);
                    }
                    break;
                case `#include`:
                    if (Array.isArray(value)) {
                        for (const item of value) {
                            const defs = Object.keys(item);
                            const includeName = defs[0];
                            const path = item[includeName];
                            await AllSpeak_Webson.include(element, includeName, path, symbols);
                        }
                    } else if (typeof value === `object`) {
                        const defs = Object.keys(value);
                        const includeName = defs[0];
                        const path = value[includeName];
                        await AllSpeak_Webson.include(element, includeName, path, symbols);
                    } else {
                        await AllSpeak_Webson.include(element, value, value, symbols);
                    }
                    break;
                case `#switch`:
                    for (let state of Object.keys(value)) {
                        if (state === symbols[`#state`]) {
                            await AllSpeak_Webson.build(element, value[state], symbols[value[state]], symbols);
                            return;
                        }
                    }
                    await AllSpeak_Webson.build(element, name, symbols[value[`default`]], symbols);
                    return;
                case `#onClick`:
                    element.onClickItems = value;
                    element.onclick = function (event) {
                        event.stopPropagation();
                        for (let state of Object.keys(element.onClickItems)) {
                            if (state === symbols[`#state`]) {
                                AllSpeak_Webson.parent.replaceChildren();
                                void AllSpeak_Webson.build(AllSpeak_Webson.parent, AllSpeak_Webson.name, AllSpeak_Webson.script, {
                                    "debug": 0,
                                    "#state": value[state]
                                });
                                return false;
                            }
                        }
                        return false;
                    };
                    break;
                default:
                    if (key[0] === `@`) {
                        const aName = key.substring(1);
                        const aValue = AllSpeak_Webson.expand(parent, value, symbols);
                        if (typeof aValue === `undefined`) {
                            throw Error(`Element ${value} could not be found`);
                        }
                        element.setAttribute(aName, aValue);
                        if (symbols[`#debug`] >= 2) {
                            console.log(`Attribute ${aName}: ${JSON.stringify(value, 0, 0)} -> ${aValue}`);
                        }
                    } else if (key[0] === `$`) {
                        // If the value is a definition object (has #element), it may be
                        // a component that should be rendered. Check whether to auto-build:
                        //   - skip if listed in the current node's own # array (avoids
                        //     duplicates when # processes it after the property loop)
                        //   - skip if a sibling $ component's # array references it
                        //     (the sibling's # processing will nest it correctly)
                        const isDefinition = typeof value === `object`
                            && !Array.isArray(value) && value !== null
                            && typeof value[`#element`] !== `undefined`;
                        let skipAutoBuild = false;
                        if (isDefinition) {
                            const ownChildren = items[`#`];
                            if (Array.isArray(ownChildren) && ownChildren.includes(key)) {
                                skipAutoBuild = true;
                            } else if (!Array.isArray(ownChildren) && typeof ownChildren === `string` && ownChildren[0] === `$` && ownChildren === key) {
                                skipAutoBuild = true;
                            } else {
                                for (const k of Object.keys(items)) {
                                    const v = items[k];
                                    if (k[0] === `$` && k !== key && typeof v === `object`
                                        && v !== null && Array.isArray(v[`#`])
                                        && v[`#`].includes(key)) {
                                        skipAutoBuild = true;
                                        break;
                                    }
                                }
                            }
                        }
                        if (isDefinition && !skipAutoBuild) {
                            await AllSpeak_Webson.build(element, key, symbols[key], symbols);
                        } else {
                            const userVal = AllSpeak_Webson.expand(element, value, symbols);
                            symbols[key] = userVal;
                        }
                        if (symbols[`#debug`] >= 2) {
                            console.log(`Variable ${key}: ${JSON.stringify(value, 0, 0)} -> ${symbols[key]}`);
                        }
                    } else {
                        const styleVal = AllSpeak_Webson.expand(element, value, symbols);
                        if (key.includes(`-`) || key.startsWith(`--`)) {
                            element.style.setProperty(key, styleVal);
                        } else {
                            element.style[key] = styleVal;
                        }
                        if (symbols[`#debug`] >= 2) {
                            console.log(`Style ${key}: ${JSON.stringify(value, 0, 0)} -> ${styleVal}`);
                        }
                    }
                    break;
            }
        }

        if (typeof items[`#`] !== `undefined`) {
            const data = items[`#`];
            if (Array.isArray(data)) {
                for (let idx = 0; idx < data.length; idx++) {
                    const child = data[idx];
                    if (typeof child === `string` && child[0] === `$`) {
                        await AllSpeak_Webson.build(element, child, symbols[child], symbols);
                    } else if (typeof child === `object` && child !== null) {
                        const childName = child[`@id`] || `#${idx}`;
                        await AllSpeak_Webson.build(element, childName, child, symbols);
                    }
                }
            } else if (typeof data === `string` && data[0] === `$`) {
                await AllSpeak_Webson.build(element, data, symbols[data], symbols);
            }
        }

        const waitStartedAt = AllSpeak_Webson.nowMs();
        await AllSpeak_Webson.waitForElementReady(element);
        const waitElapsed = Math.round(Webson.nowMs() - waitStartedAt);
        const totalElapsed = Math.round(AllSpeak_Webson.nowMs() - buildStartedAt);
        const tag = element && element.tagName ? element.tagName.toLowerCase() : `unknown`;
        AllSpeak_Webson.reportTiming(`[WebsonTiming] name='${name}' tag='${tag}' wait=${waitElapsed}ms total=${totalElapsed}ms`);
    },

    // Render a script into a given container
    render: async (parent, name, script, options = {}) => {
        AllSpeak_Webson.parent = parent;
        AllSpeak_Webson.name = name;
        AllSpeak_Webson.script = typeof script === `string` ? JSON.parse(script) : script;
        AllSpeak_Webson.timingEnabled = !!options.timingEnabled;
        AllSpeak_Webson.timingReporter = typeof options.timingReporter === `function`
            ? options.timingReporter
            : null;
        await AllSpeak_Webson.build(parent, name, AllSpeak_Webson.script, {
            "#debug": Number.isFinite(options.debug) ? options.debug : 0,
            "#state": options.state || "default"
        });
    }
};

if (typeof globalThis !== `undefined`) {
    globalThis.Webson = AllSpeak_Webson;
}

if (typeof module !== `undefined` && module.exports) {
    module.exports = AllSpeak_Webson;
}
